postgresdb:
  #image: postgres
  build: postgresdb
  environment:
    POSTGRES_USER: mjolnir
  ports:
    - 5432:5432

apacheds:
  #image: h3nrik/apacheds
  build: apacheds
  ports:
    - 10389:10389
    - 6088/udp:6088/udp

wildfly:
  #image: jboss/wildfly
  build: wildfly/
  links:
    - postgresdb:db
    - apacheds:ds
  ports:
    - 8080:8080
    - 8443:8443
    - 8787:8787
    - 9990:9990
